### ISSUE TITLE
`num_workers` doesn't seem to work as intended

### ISSUE THREAD

**Issue by Syzygianinfern0** [metadriverse/scenarionet#12]
I use `--num_workers 12` but htop still shows only two cores with 100% utilization. I'm not sure why though as 

https://github.com/metadriverse/scenarionet/blob/e9c1419a91c42e67fe176a538d2984cf1d9e0f93/scenarionet/converter/utils.py#L124

seems to be right 🤔

**Comment by QuanyiLi** [comment]
Hi, sorry for the late reply. I didn't watch this repo until now...

Could you tell me which dataset you are converting? I can not reproduce this issue. Thank you!
