### ISSUE TITLE
Errors when converting nuScenes dataset

### ISSUE THREAD

**Issue by jongchyisu** [metadriverse/scenarionet#13]
Hello, thanks for the great work! 
I'm trying to convert the nuScenes dataset, however I got several errors:
1. There are scenes with velocity >50 and causing the assertion error. Is there something wrong for velocity measurement or is the velocity correct?
2. I then got error of `ValueError: could not broadcast input array from shape (193,3) into shape (191,3)` at this line https://github.com/metadriverse/scenarionet/blob/e9c1419a91c42e67fe176a538d2984cf1d9e0f93/scenarionet/converter/nuscenes/utils.py#L206C13-L206C81  What's the issue of this?
3. How do you deal with multiprocessing's OOM error (shows "killed")?

Thanks for your time!

**Comment by QuanyiLi** [comment]
Hi, sorry for the late reply. I didn't watch this repo until now... 

For your questions:

1. nuScenes data is actually collected in a low frequency, so I interpolate the data to make them 10hz. To make sure the interpolation won't generate some outliers, I add that some assert. Just ignore them for free. 

2. Could you tell me which nuScenes split you are using? There must be something wrong in the interpolation process. It is currently tested on the nuPlan-mini only. I will check them later

3. Lower the number of workers can solve this like 'num_workers=2'

I will fix the bugs and update the progress soon.

**Comment by 33zzstar** [comment]
Hello, when I execute convert_nuscenes. py on multiple threads, there are always some threads that cannot be processed and get stuck. Excluding the situation of insufficient memory, can we only reprocess the data in this case? What should we do? Also, I noticed that there is no test version (replaced by val?) when processing the nuscenes dataset. What is the difference between trainnval and train? Which version should I handle if I want to train?
