### ISSUE TITLE
Code request for multi-agent cooperative learning

### ISSUE THREAD

**Issue by Kguo-cs** [metadriverse/scenarionet#14]
Could you provide the code for multi-agent cooperative learning in your paper such as (GAIL,AIRL)? Thank you in advance.

**Comment by QuanyiLi** [comment]
@pengzhenghao Could you help with this?

**Comment by pengzhenghao** [comment]
We are preparing the release and will provide the training code as well as the result when ready.

**Comment by Kguo-cs** [comment]
Could you tell me when this training code as well as the result will be available?

**Comment by Kguo-cs** [comment]
It seems that the code for multi-agent cooperative learning is still unavailable now. Will you release that any more?
