### ISSUE TITLE
Question regarding centerlines and traffic lights

### ISSUE THREAD

**Issue by Syzygianinfern0** [metadriverse/scenarionet#16]
Is the centerline data of lanes extracted from the nuPlan scenarios? I only see inner and outer lane boundaries which are `ROAD_LINE_BROKEN_SINGLE_WHITE` and `ROAD_LINE_SOLID_SINGLE_WHITE`. But I don't find data related to the centerline.

Secondly, regarding traffic lights, The start positions of the lanes are present as part of the `stop_point` key in the extracted data. How can this be mapped to which lane it is? Since there is no information regarding the centerline, I am not sure how to map the start positions of lanes to the map.

**Comment by QuanyiLi** [comment]
Hi, sorry for the late reply.

Regarding your questions,

1. The centerline is called `LANE_SURFACE_STREET`.

2. Actually, we don't use the `stop_point`, as some data provides it like Waymo but some don't contain this information like nuPlan. However, all dataset actually records which lane the light is on. Thus we also record them in the field: 'TRAFFIC_LIGHT_LANE'

We will elaborate on the data structure in the document soon!
