### ISSUE TITLE
How to replicate the results of PPO trained by nuPlan dataset?

### ISSUE THREAD

**Issue by Liuxueyi** [metadriverse/scenarionet#17]
Could you give the training command and requirements.txt? It is hard to replicate the training environment for me. And if you train the PPO agent using the Waymo dataset?
Looking forward to your reply, thanks.

**Comment by QuanyiLi** [comment]
Hi, sorry for the late reply. I didn't watch this repo until now...

To run the training scripts, follow these steps:
1. Create a new conda env and make sure the python==3.8
2. Clone ScenarioNet and MetaDrive, install them via ```pip install -e .[train]``` and ```pip install -e .``` respectively
3. Run any of the training scripts under `scenarionet/scenarionet_training/scripts`

Before this, you should setup the dataset correctly.
