### ISSUE TITLE
Question regarding conflicting dependencies

### ISSUE THREAD

**Issue by wisleythewise** [metadriverse/scenarionet#29]
I have installed scenarionet and metadrive successfully but when I run the following command to install the waymo-open-dataset on ubuntu 20.04 LTS through WSL 2 

pip install waymo-open-dataset-tf-2-11-0==1.5.0

I get the following error ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behavior is the source of the following dependency conflicts.
seaborn 0.13.0 requires matplotlib!=3.6.1,>=3.3, but you have matplotlib 3.6.1 which is incompatible.
metadrive-simulator 0.4.1.2 requires numpy<=1.24.2,>=1.21.6, but you have numpy 1.21.5 which is incompatible.
scenarionet 0.0.1 requires numpy<=1.24.2,>=1.21.6, but you have numpy 1.21.5 which is incompatible.

This is how I installed scenarionet and metadrive

mkdir mdsn
cd mdsn

git clone https://github.com:metadriverse/metadrive.git
cd metadrive
pip install -e.
cd ../

git clone https://github.com:metadriverse/scenarionet.git
cd scenarionet
pip install -e .

The other proposed method to install waymo

pip install -e .[waymo] 

Resulted in the following error

ERROR: Cannot install scenarionet because these package versions have conflicting dependencies.

The conflict is caused by:
    tensorflow 2.11.0 depends on protobuf<3.20 and >=3.9.2
    metadrive-simulator 0.4.1.1 depends on protobuf==3.20.3

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by QuanyiLi** [comment]
Thank you for the feedback! We are going to fix it.

In your first trial, does it work? I think pip now just throws the error message, and will keep installing packages with conflicts.

**Comment by QuanyiLi** [comment]
Actually, I removed the dependency for `protobug` in `metadrive-simulator=0.4.1.2`. Could you upgrade your MetaDrive version before using the second way to install it?

**Comment by wisleythewise** [comment]
The following error occurred:
`
pip install pip install "metadrive-simulator==0.4.1.2"
git clone https://github.com:metadriverse/scenarionet.git
cd scenarionet
pip install -e .[waymo]
`

Resulted in the the same error, it seems that the metadrive-simulator versions is reverted back

**Comment by wisleythewise** [comment]
The error still shows but running pip check results in no error's so the issue has been resolved thank you!

**Comment by wisleythewise** [comment]
It solved my problem, thank you!
