### ISSUE TITLE
Is there an example of NuPlan dataset?

### ISSUE THREAD

**Issue by CarlDegio** [metadriverse/scenarionet#32]
I found that there is an example of nusense datasets, but I don't know if nuplan is already supported? I found this when using metadrive: `WARNING:metadrive.utils.nuplan:This converters will de deprecated. Use tools in ScenarioNet instead: https://github.com/metadriverse/ScenarioNet`. So I found here.

**Comment by QuanyiLi** [comment]
Please check our doc first: https://scenarionet.readthedocs.io/en/latest/. The mini Waymo example would provide you with basic ideas about how ScenarioNet works. For using nuPlan data, just apply the nuPlan converter to turn the data into our scenario description.

**Comment by CarlDegio** [comment]
Sorry to bother, I ignored the documentation and only noticed the tutorial. The tip for nuplan converter is useful, I have found the information. Thank you!
