### ISSUE TITLE
normalize all positions with ego car's first frame position as origin

### ISSUE THREAD

**Issue by QuanyiLi** [metadriverse/scenarionet#56]
There is a function `ScenaioDescription.centralize_to_ego_car_initial_position()` which should be called after processing all scenarios, especially Waymo Scenarios.

**Comment by pengzhenghao** [comment]
why?

**Comment by QuanyiLi** [comment]
The simulator needs to centralize all elements to (0,0) so the terrain can be generated. But No need to do this now. We can normalize them on the simulator side.
