### ISSUE TITLE
Lane centre polylines in nuscenes after conversion seem to be uncentred wrt map

### ISSUE THREAD

**Issue by samueleruffino99** [metadriverse/scenarionet#66]
Hello,
I have converted a nuscenes scenario, and when i am printing out the whole map element I get this strange behavior, the lanes' center lines are not centered with the other map elements.
![Screenshot 2024-02-23 145823](https://github.com/metadriverse/scenarionet/assets/127489168/0b07c5b2-d77c-4a10-991b-23e3c5e8ddcd)
I think it might be an error on how to compute the map_centre of the polylines in converter/nuscenes.utils.py?
`result[SD.TRACKS], map_center = get_tracks_from_frames(nuscenes, scene_info, frames, num_to_interpolate=5)
.......
Normalize place all object to (0,0)
    map_center = np.array(interpolate_tracks["ego"]["state"]["position"][0])
    map_center[-1] = 0
    normalized_ret = {}
    for id, track, in interpolate_tracks.items():
        pos = track["state"]["position"] - map_center
        track["state"]["position"] = np.asarray(pos)
        normalized_ret[id] = track`

**Comment by QuanyiLi** [comment]
I confirmed this error. It is introduced in a recent PR. I have fixed it now. Please pull the latest code

**Comment by samueleruffino99** [comment]
Thank you so much!
