### ISSUE TITLE
Some questions about Navigation

### ISSUE THREAD

**Issue by FanYi-arch** [metadriverse/scenarionet#80]
I tried masking the navigation information while training the nuplan dataset, but the training got worse. In the process of understanding the code I noticed that scenario_description contains SDC_ID and based on SDC_ID I can get sdc_track. what does SDC_ID and sdc_track mean respectively? Looking forward to your reply.

**Comment by QuanyiLi** [comment]
Usually, most self-driving data are collected by data-collection cars in an ego-centric manner. This car is referred to as SDC (self-driving-car) or AV (autonomous car). And thus the training goal is to follow the trajectory of the SDC.
