### ISSUE TITLE
Custom dataset convertors 

### ISSUE THREAD

**Issue by bob020416** [metadriverse/scenarionet#90]
Hi, thanks for the great work,
I have a dronalized dataset like inD.SinD.. 
But i found most of the convertor is now using sensor based dataset 

I have my data with (time, type , position , velocities , width and height and radian) and i have a map with osm lanelet2 format 

Do you think it is possible to write a convertor for drone based dataset ? 
and i'm wondering have you consider put INTERACTION inD... such dataset into your framework 

If it is possible can you tell the workload ?

many thanks

**Comment by QuanyiLi** [comment]
Yes. It would be possible. 

1. What the convertor did is to extract positions/headings/velocities/sizes from these sensor-based datasets. You can finish the trajectory part by simply organizing your data into the target format.
2. For the map part, this [`extrac_map_features()`](https://github.com/metadriverse/metadrive/blob/main/metadrive/manager/sumo_map_manager.py#L6) function allows you to extract the map features in the ScenarioNet format with a SUMO map, which can be converted from an osm map. [This is another script](https://github.com/metadriverse/metadrive/blob/ee5e1f8321ed0423a82c466132970f2dbbbc622a/metadrive/tests/vis_env/vis_sumo_map.py#L11) to build a simulation from a sumo map, which maybe helpful too.

When building the convertor, I suggest first building the map convert part and adding a dummy vehicle at position [0, 0]. Then test it. If the simulation can be launched with this converted file. Go add the trajectory processing part into the convert function. I managed to convert in-house drone data to this format before, so it should work as well.

**Comment by bob020416** [comment]
Thank you, I'll try it! 

> Yes. It would be possible. 
> 
> 1. What the convertor did is to extract positions/headings/velocities/sizes from these sensor-based datasets. You can finish the trajectory part by simply organizing your data into the target format.
> 2. For the map part, this [`extrac_map_features()`](https://github.com/metadriverse/metadrive/blob/main/metadrive/manager/sumo_map_manager.py#L6) function allows you to extract the map features in the ScenarioNet format with a SUMO map, which can be converted from an osm map. [This is another script](https://github.com/metadriverse/metadrive/blob/ee5e1f8321ed0423a82c466132970f2dbbbc622a/metadrive/tests/vis_env/vis_sumo_map.py#L11) to build a simulation from a sumo map, which maybe helpful too.
> 
> When building the convertor, I suggest first building the map convert part and adding a dummy vehicle at position [0, 0]. Then test it. If the simulation can be launched with this converted file. Go add the trajectory processing part into the convert function. I managed to convert in-house drone data to this format before, so it should work as well.
