### ISSUE TITLE
Incompatible shapely version when used with nuscenes-devkit

### ISSUE THREAD

**Issue by keroe** [metadriverse/scenarionet#92]
Scenarionet needs geopandas installed, but geopandas dropped support for shapely<2
![image](https://github.com/user-attachments/assets/ed783d84-ea73-4c5d-af93-211b66dd63f1)
This results in conflicts when the nuscenes-devkit is installed in the same python environment, because the devkit relies on [shapely<2.0](https://github.com/nutonomy/nuscenes-devkit/blob/master/setup/requirements/requirements_base.txt#L11).
Pip will install geopandas > 1.0.

**Comment by pengzhenghao** [comment]
Thanks for rasing this issue!
